<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.10.0 on win32)" generated="20211103 15:24:54.160" rpa="false" schemaversion="2">
<suite id="s1" name="Hyper2" source="C:\Users\10135\.ssh\testehypeflame\testehypeflame\tests\hyper2.robot">
<test id="s1-t1" name="Desafio">
<kw name="Abrir navegador" type="SETUP">
<msg timestamp="20211103 15:24:54.452" level="FAIL">No keyword with name 'Abrir navegador' found.</msg>
<status status="FAIL" starttime="20211103 15:24:54.452" endtime="20211103 15:24:54.452"/>
</kw>
<kw name="Fechar navegador" type="TEARDOWN">
<msg timestamp="20211103 15:24:54.454" level="FAIL">No keyword with name 'Fechar navegador' found.</msg>
<status status="FAIL" starttime="20211103 15:24:54.454" endtime="20211103 15:24:54.455">No keyword with name 'Fechar navegador' found.</status>
</kw>
<status status="FAIL" starttime="20211103 15:24:54.449" endtime="20211103 15:24:54.455">Setup failed:
No keyword with name 'Abrir navegador' found.

Also teardown failed:
No keyword with name 'Fechar navegador' found.</status>
</test>
<status status="FAIL" starttime="20211103 15:24:54.165" endtime="20211103 15:24:54.457"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Hyper2">Hyper2</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211103 15:24:54.448" level="ERROR">Error in file 'C:\Users\10135\.ssh\testehypeflame\testehypeflame\tests\hyper2.robot' on line 4: Resource file '..\resource\hyper1.robot' does not exist.</msg>
</errors>
</robot>
